In [2]:
import tensorflow as tf
import numpy as np

In [8]:
escalar = tf.Variable(1342, shape = (), dtype = tf.int16)
print(escalar)

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=1342>


In [11]:
my_tensor = tf.constant([[1.0,2.0], [3.0,4.0]])

In [14]:
vector_fila = tf.Variable([1,2,3,4],shape = (4,), dtype = tf.int16)
print(vector_fila)

<tf.Variable 'Variable:0' shape=(4,) dtype=int16, numpy=array([1, 2, 3, 4], dtype=int16)>


In [21]:
vectorCol = tf.Variable([[12], [21], [21], [12]], shape = (4,1), dtype = tf.int32)
print(vectorCol)

<tf.Variable 'Variable:0' shape=(4, 1) dtype=int32, numpy=
array([[12],
       [21],
       [21],
       [12]], dtype=int32)>


In [27]:
matriz = tf.Variable([[1,2,3],[2,3,4],[3,4,5],[4,5,6]], shape = (4,3), dtype = tf.int16)
matriz

<tf.Variable 'Variable:0' shape=(4, 3) dtype=int16, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]], dtype=int16)>

In [28]:
texto = tf.Variable("Este registro fue generado con la información de los clientes", shape = (), dtype= tf.string)
print(texto)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Este registro fue generado con la informaci\xc3\xb3n de los clientes'>


In [32]:
constante = tf.constant([34,3,21], shape = (3,), dtype = tf.int16)
constante

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([34,  3, 21], dtype=int16)>